// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc5919Vok48TeLQUPEgqKB8sCLgPEA0kk',
    appId: '1:432405771305:android:5604388ba49b995ebe5838',
    messagingSenderId: '432405771305',
    projectId: 'bdmarket-726ff',
    storageBucket: 'bdmarket-726ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc6nEn7XTkNddsgE9-XJ723Ufg3Jt_f8Q',
    appId: '1:432405771305:ios:d31e7acbf9032505be5838',
    messagingSenderId: '432405771305',
    projectId: 'bdmarket-726ff',
    storageBucket: 'bdmarket-726ff.firebasestorage.app',
    androidClientId: '432405771305-2euhe0p2iul9ua9b8263l3mcpf3fsql0.apps.googleusercontent.com',
    iosClientId: '432405771305-pr2nicoj1ksr88lfpj1q85orpmvor98n.apps.googleusercontent.com',
    iosBundleId: 'com.mysenger.ali',
  );
}
